config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :users do
    resources :assignments
  end
  
  resources :lists do
    resources :items
  end

  root 'lists#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :item

  

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list # Adds methods to my model
  has_many :users, through: :assignments
  has_many :assignments
  validates :description, presence: true

  STATUS = {
    incomplete: 0,
    complete: 1
  }

  def complete?
    self.status == STATUS[:complete]
  end

  def incomplete?
    self.status == STATUS[:incomplete]
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items # Adds methods to my model
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {email.downcase!}
  validates :name, presence: true, length: {maximum: 50}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true, length: {minimum: 6}
  has_many :lists
  has_many :items, through: :lists
  has_many :assignments, through: :items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authentication_required
    if !logged_in?
      redirect_to login_path
    end
  end

  # def logged_in?
  #   !!current_user
  # end

  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end

  # Methods you build in controllers do not permeate to your ActionView part of your code
  # So you can't call this in your html.erb unless you say explicitly.
  # So explicitly stating this is a helper method, please let me use it in my view...
  helper_method :current_user

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  def create
  end

  def update
  end

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id]) # finding the parent
    @item = @list.items.build(item_params)
    if @item.save
      redirect_to list_path(@list)
    else
      render "lists/show"
    end
    # raise @item.inspect
  end

  # PATCH - /lists/:list_id/items/:id
  def update
    # raise params.inspect # the data the form submitted
    # I can use that data to update the item described in the URL
    @item = Item.find(params[:id])
    @item.update(item_params)
    # @item.status = params[:item][:status]
    # @item.save

    redirect_to list_path(@item.list)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to list_path(@item.list)
  end

  private
    def item_params
      params.require(:item).permit(:description, :status)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authentication_required

  def index
    # if you're not logged in, you can't see this, in fact, go back to the log in page
    @list = List.new
    @lists = List.all
    # raise @lists.inspect # was the controller able to get the lists from the DB
    # implicit rendering lists/index (controller/action)
  end

  def show
    # load lists
    # params will have all the data passed by a user
    @list = List.find(params[:id])
    @item = Item.new
  end

  def create
    #raise params.inspect
    @list = List.new(list_params)
    if @list.save
      redirect_to list_url(@list)
    else
      @lists = List.all
      render :index
    end
  end

  private

    def list_params # strong parameters
      params.require(:list).permit(:name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new # login page in views/sessions/new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
      flash[:success] = 'Welcome to Task Tracker! You are now logged in.'
      #redirect_to root_path 
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Task Tracker! You are now logged in."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def li_class_for_item(item)
    "completed" if item.complete?
  end

  def li_for_item(item)
    content_tag_for :li, item, class: li_class_for_item(item) do
      yield
    end
  end

  def form_for_item_status(item)
    form_for([item.list, item]) do |f|
      f.check_box :status, class: "toggle", checked: item.complete?
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #credit (h/t) to michael hartl of www.railstutorial.org
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session. (Ch 9: adv login)
  # def remember(user)
  #   user.remember
  #   cookies.permanent.signed[:user_id] = user.id
  #   cookies.permanent[:remember_token] = user.remember_token
  # end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def logged_in?
    !!current_user # same as saying current_user.nil?
  end

  def log_out #redundant with reset_session available in ActionController::Base
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>
  <div class="view">

    <%= form_for_item_status(item) %>

    <label><%= item.description %></label>

    <%= button_to "x", list_item_path(item.list, item), method: :delete, class: :destroy %>
  
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
    <%= yield %>
  </body>

  <footer>
    <% flash.each do |message_type, message| %>
      <div class="footer"><%= message %></div>
    <% end %>
  </footer>

</html>

app/views/lists/index.html.erb
<section class="todoapp">
  <header class="header">
    <h1>Your Lists</h1>
      <%= form_for(@list) do |f| %>
        <%= f.text_field :name, class: "new-todo", autofocus: true, placeholder: @list.errors.full_messages_for(:name).first || "Enter a new list name..."   %></br>
        <%= f.submit %>
      <% end %>
  </header>

  <section class="main">
    <ul class="todo-list">
      <% @lists.each do |list| %>
      <li>
        <div class="view">
            <label><%= link_to list.name, list_path(list) %></label>
        </div>
      </li>
      <% end %>
    </ul>
  </section>

  <footer class="footer">
    <ul class="filters">
      <li><%= link_to "signup", signup_path %></li>
      <li><%= link_to "logout", logout_path %></li>
    </ul>
  </footer>
</section>

<footer class="info">
  <h3>You are currently logged in as <%= current_user.name unless !logged_in? %></h3>
</footer>

app/views/lists/show.html.erb
<section class="todoapp">
  <header class="header">
    <h1><%= @list.name %></h1>
    <%= form_for([@list, @item]) do |f| %>
        <%= f.text_field :description, class: "new-todo", autofocus: true, placeholder: @item.errors.full_messages_for(:description).first || "Enter a new item..." %></br>
        <%= f.submit :style => "display: none" %>
    <% end %>
  </header>

  <section class="main">
    <ul class="todo-list">
    <%= render collection: @list.items, partial: "items/item_li", as: :item %>
    
    </ul>
  </section>

  <footer class="footer">
    <ul class="filters">
      <li><%= link_to "home", root_path %></li>
      <li><%= link_to "signup", signup_path %></li>
      <li><%= link_to "logout", logout_path %></li>
    </ul>
  </footer>

</section>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div class="todo">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/create.html.erb
create.html.erb

app/views/users/new.html.erb
<section class="todoapp">
  <header class="header">
    <h1>New User Registration!</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.text_field :name, class: "new-todo", placeholder: "Name" %>
      <%= f.email_field :email, class: "new-todo", placeholder: "Login Email" %>
      <%= f.password_field :password, class: "new-todo", placeholder: "Choose your new password" %>
      <%= f.password_field :password_confirmation, class: "new-todo", placeholder: "Re-type your password" %>
      <%= f.submit "Create my account", class: "hidden" %>
      <% end %>

  </header>

  <footer class="footer">

  </footer>

</section>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>

<footer>
  <p><label>email:</label> <%= @user.email %> <%= link_to "update", edit_user_path(@user) %></p>
  <p><%= Time.now %></p>
</footer>